# Site wide config:

title: "Combinatorics Through Guided Discovery"
description: "by Kenneth P. Bogart"

footer: "Page &#169; Copyright 2018 Oscar Levin for OpenMathBooks.org"

sass:
  style: compressed
